// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYIn0yddAug4GTW_G6WPWpaFOfnUrpysA',
    appId: '1:1006715825786:web:41bffe642d5e74ae6895c3',
    messagingSenderId: '1006715825786',
    projectId: 'moviesapp-25b64',
    authDomain: 'moviesapp-25b64.firebaseapp.com',
    storageBucket: 'moviesapp-25b64.appspot.com',
    measurementId: 'G-YXL5NG5889',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1r496T8T5S1y0sJcWZ0XJz2D0k3Z57aQ',
    appId: '1:1006715825786:android:7132de4d338fe8ca6895c3',
    messagingSenderId: '1006715825786',
    projectId: 'moviesapp-25b64',
    storageBucket: 'moviesapp-25b64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuUJxT68hZ9vmzw9lkOJsdw7vobMIRk8E',
    appId: '1:1006715825786:ios:d95cb706a56653d66895c3',
    messagingSenderId: '1006715825786',
    projectId: 'moviesapp-25b64',
    storageBucket: 'moviesapp-25b64.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuUJxT68hZ9vmzw9lkOJsdw7vobMIRk8E',
    appId: '1:1006715825786:ios:3352f8d2e8905bc56895c3',
    messagingSenderId: '1006715825786',
    projectId: 'moviesapp-25b64',
    storageBucket: 'moviesapp-25b64.appspot.com',
    iosBundleId: 'com.example.moviesApp.RunnerTests',
  );
}
